#if !defined			MAX_PLAYER_PASSWORD
    #define				MAX_PLAYER_PASSWORD			        (24)
#endif

#if !defined			MIN_PLAYER_PASSWORD
    #define				MIN_PLAYER_PASSWORD			        (6)
#endif

#if !defined			MAX_PLAYER_EMAIL
    #define				MAX_PLAYER_EMAIL			        (35)
#endif

#if !defined			MIN_PLAYER_EMAIL
    #define				MIN_PLAYER_EMAIL			        (6)
#endif

#if !defined            MAX_LENGTH_IP
    #define             MAX_LENGTH_IP                       (16)
#endif

#if !defined            MAX_LENGTH_DATE
    #define             MAX_LENGTH_DATE                     (19)
#endif

#if !defined            SET_START_CAPITAL
    #define             SET_START_CAPITAL                   (150)
#endif

#if !defined            SET_START_SCORE
    #define             SET_START_SCORE                     (1)


#define					FULL_PROJECT_NAME					"Filder Role Play | Ineo | Обновление."
#define					HASTILY_PROJECT_NAME				"FRP | Ineo | Обновление"

#define					MYSQL_HOST							"149.202.88.119"
#define					MYSQL_USER							"gs256520"
#define					MYSQL_PASS							"asdewqzxc132_"
#define					MYSQL_DATA							"gs256520"

#define                 MAX_CAMERA_SPAWN                     (2)